package dev.staeming.configreader.internal

import dev.staeming.configreader.ConfigValues
import dev.staeming.configreader.internal.Mapper.propertiesMapper
import dev.staeming.configreader.internal.Mapper.ymlMapper
import java.io.File
import java.nio.file.Path
import java.nio.file.Paths
import kotlin.io.path.exists

internal class FileManager {
    private var configFile : File

    constructor(path: Path){
        val file = path.toFile()

        if(!path.exists()){
            if(file.parentFile != null && !file.parentFile.exists()){
                file.parentFile.mkdirs()
            }
            file.createNewFile()
        }
        configFile = file
    }

    constructor(pathString: String): this(Paths.get(pathString))

    fun writeFile(values: ConfigValues) {
        val ext = configFile.extension.lowercase()

        when(ext) {
            "yml", "yaml" -> {
                val ymlString = ymlMapper.writeValueAsString(values)
                configFile.writeText(ymlString)
            }
            "properties" -> {
                val props = propertiesMapper.writeValueAsProperties(values)
                configFile.outputStream().use { os ->
                    props.store(os, "Generated by ConfigReader")
                }
            }
        }
    }

    fun <T: ConfigValues>writeFile(clazz: Class<out T>) {
        val defaultInstance = clazz.getDeclaredConstructor().newInstance()
        writeFile(defaultInstance)
    }
}